### ISSUE TITLE
Add optional Promise API

### ISSUE THREAD

**Issue by Marak** [bigcompany/hook.io-sdk#1]
Summoning @monkbroc

As per https://github.com/bigcompany/hook.io/commit/09cd65a0891e99ad18097ecf776d17559c57a476 , the `hook.io-datastore` API is no longer directly available to the worker environment.

Instead of allowing the workers to communicate with redis directly, we are now using `hook.io-sdk` and the public hook.io HTTP API with API Access Keys.

The end-user API inside hook services for `datastore` will remain exactly the same. The only difference we have now, is that `hook.io-datastore` has a Promises API, and `hook.io-sdk` does not.

It should be easy for me to add `thenify` to `hook.io-sdk`. 

Hopefully, this change won't break or affect any existing services.

**Comment by Marak** [comment]
That was actually much easier than I thought.

I was able to iterate through all the API methods and apply `thenify`.

This should make further maintenance much easier.

@monkbroc -

Will try to deploy this in the next few days. Hopefully when we switch the `datastore` API all existing services will remain unaffected.

**Comment by monkbroc** [comment]
I'm glad you were able to use my datastore PR as a template for this change to the new API library.

Thanks for your continued work on hook.io!
