### ISSUE TITLE
client.hook.update() logs out of the hook.io platform and returns no response

### ISSUE THREAD

**Issue by chriskruse** [bigcompany/hook.io-sdk#5]
Attempting to update an existing microservice via the REST API and node sdk. The `create` and `delete` methods work as expected. The `update` method returns no results. Instead, it kicks you out of the system.

I have tried to run my hook which updates another hook. All code executes fine, but once I reach the `hook.update()` method, the system logs me out (after a few seconds. Timeout never reached). The browser returns an error (screen attached).

Sample of the code:

```
var client = hookIO.createClient({ hook_private_key: hook.env['key'] });
var service = {}; //data as expected

client.hook.update('name-of-service', service, function(err, res) {
     hook.res.end({ err: err, res: res });
});
```

![screen shot 2016-07-28 at 12 19 53 pm](https://cloud.githubusercontent.com/assets/13278276/17220550/bde07f38-54bd-11e6-8346-6560e89e6539.png)

**Comment by Marak** [comment]
Sorry for the trouble.

I'll look into it today and see if we can resolve it.

I suspect we have this resolved locally, but not deployed to production yet.

**Comment by andrewtlove** [comment]
Going to echo this error.  Using an analogue of the sample code at [examples/hook-update.js](https://github.com/bigcompany/hook.io-sdk/blob/f2383161bdc2e415add74efd72d3b1ca6540f2a3/examples/hook-update.js), I receive the following error:

``` bash
{ Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

**Comment by Marak** [comment]
Confirmed it's resolved locally. Need to push an update out.

Will try to have a deployment out this week.

**Comment by Marak** [comment]
This should now be hot-patched in production, was a one line fix.

Commits will be coming soon.

**Comment by andrewtlove** [comment]
Just tested and can verify it works!  Thanks for fixing so quickly!

**Comment by Marak** [comment]
Closing issue.

Problem was related to back-end fix to hook.io itself, but I never came back here to cross reference the commit.

We also have unit tests for hook resource operations, so hopefully we won't see this regress again.
