### ISSUE TITLE
(doc) Please clarify plans on "domains" object

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io-sdk#7]
There are "[Domains - won't be added](https://github.com/bigcompany/hook.io-sdk/blob/fd3f7035d8e7a4065fc422c65fadb5a14e94f399/ReadMe.md#available-endpoints)" note in ReadMe.md - could you explain this?

**Comment by Marak** [comment]
@pyhedgehog -

Sorry about that.

Comment seems wrong. I've added `domains` and also `hook-alias` CLI commands for managing domains.

Still needs a little work, is in `dev` branch atm.
