### ISSUE TITLE
branch dev broken dependencies

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io-sdk#8]
[package.json#L38](https://github.com/bigcompany/hook.io-sdk/blob/a5368245d145e0e2ce8ecb86a3aa504450b5ccf9/package.json#L38): [mschema-prompt](https://www.npmjs.com/package/mschema-prompt)
[package.json#L35](https://github.com/bigcompany/hook.io-sdk/blob/a5368245d145e0e2ce8ecb86a3aa504450b5ccf9/package.json#L35): [microservice-examples](https://www.npmjs.com/package/microservice-examples)

**Comment by Marak** [comment]
I'll get this resolved today. Working on it now.

**Comment by Marak** [comment]
Okay, just released: https://github.com/mschema/mschema-prompt

Not super thrilled I had to build `mschema-prompt`, but we needed it and have it now.

Could be nice little tool. Using it now for `package.json` init process with `hook-init` binary.

One down.

**Comment by Marak** [comment]
Okay, just published https://www.npmjs.com/package/microservice-examples

Will continue to review the SDK locally and prepare it for upcoming release.
